name: Python Unit Tests
on:
  push:
    branches:
      - main  # tested with a branch called... "- test"
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  test:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        python-version: ['3.14', '3.13', '3.12', '3.11', '3.10']
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: 'Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}'
        uses: actions/setup-python@v6.1.0
        with:
          python-version: '${{ matrix.python-version }}'
      - if: ${{ 'windows-latest' != matrix.os }}
        run: export BOTO_CONFIG=/dev/null
      - if: ${{ 'windows-latest' != matrix.os }}
        run: 'export PYTHONPATH=$PYTHONPATH:$(pwd)'
      - name: 'Set up test env'
        run: |
          pip install responses
          pip install -r requirements.txt
          pip install coveralls
      - name: 'Unit tests...'
        working-directory: ./tests
        run: coverage run --source=.. --omit=../lib/* ./all_tests.py
